name: CI

# プッシュとプルリクエストで実行
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Test job
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    # Checkout source code
    - uses: actions/checkout@v4

    # Setup Rust
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    # Cache dependencies
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    # Build
    - name: Build
      run: cargo build --verbose

    # Run tests
    - name: Test
      run: cargo test --verbose

  # Lint and format check
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    # Format check
    - name: Format check
      run: cargo fmt --all -- --check

    # Clippy check
    - name: Clippy
      run: cargo clippy -- -D warnings